:paths:
  :source:
    - src/**
  :include:
    - include
    - src
  :test:
    - src/** # unit tests live next to code

:flags:
  :preprocess:
    :compile: []

:project:
  # how to use ceedling. If you're not sure, leave this as `gem` and `?`

  :ceedling_version: 1.0.1

  # optional features. If you don't need them, keep them turned off for performance
  :use_mocks: TRUE
  :use_decorators: :auto # decorate Ceedling's output text. options are :auto, :all, or :none

  # tweak the way ceedling handles automatic tasks
  :build_root: tests_build
  :test_file_prefix: ""
  :test_file_suffix: ".test.c"
  :default_tasks:
    - test:all

  :release_build: FALSE

:plugins:
  :load_paths: []
  :enabled:
    - module_generator # handy for quickly creating source, header, and test templates
    - report_tests_pretty_stdout

:extension:
  :executable: .out

---
# Configuration Options specific to CMock. See CMock docs for details
# ====
# ====
# ====

:cmock:
  :mock_path: test/support/mocks
  :stub_path: test/support/stubs
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    :enabled:
      - :ignore
      - :callback
      - stdout_pretty_tests_report
      - module_generator
  :treat_as:
    uint8: HEX8
    uint16: HEX16
    uint32: UINT32
    int8: INT8
    bool: UINT8

################################################################
# PLUGIN CONFIGURATION
################################################################

#clang Add -gcov to the plugins list to make sure of the gcov plugin
# You will need to have gcov and gcovr both installed to make it work.
# For more information on these options, see docs in plugins/gcov
:gcov:
  :summaries: TRUE # Enable simple coverage summaries to console after tests
  :report_task: FALSE # Disabled dedicated report generation task (this enables automatic report generation)
  :utilities:
    - gcovr # Use gcovr to create the specified reports (default).
    #- ReportGenerator # Use ReportGenerator to create the specified reports.
  :reports: # Specify one or more reports to generate.
    # Make an HTML summary report.
    - HtmlBasic
  :gcovr:
    :html_medium_threshold: 75
    :html_high_threshold: 90
